name: Deploy Vue 3 Vite site to GitHub Pages

on:
  push:
    branches:
      - main  # deploy when you push to main branch

permissions:
  contents: write  # Allow writing to repository
  pages: write     # Allow writing to GitHub Pages
  id-token: write  # Allow writing ID tokens

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Vite requires Node.js >=20.19

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
